// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: andy/netty/UserProto.proto

package andy.entity;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:andy.entty.LoginProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .andy.entty.UserProto userProto = 1;</code>
     */
    boolean hasUserProto();
    /**
     * <code>required .andy.entty.UserProto userProto = 1;</code>
     */
    andy.entity.UserProtos.UserProto getUserProto();
    /**
     * <code>required .andy.entty.UserProto userProto = 1;</code>
     */
    andy.entity.UserProtos.UserProtoOrBuilder getUserProtoOrBuilder();
  }
  /**
   * Protobuf type {@code andy.entty.LoginProto}
   */
  public static final class LoginProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:andy.entty.LoginProto)
      LoginProtoOrBuilder {
    // Use LoginProto.newBuilder() to construct.
    private LoginProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginProto defaultInstance;
    public static LoginProto getDefaultInstance() {
      return defaultInstance;
    }

    public LoginProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              andy.entity.UserProtos.UserProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = userProto_.toBuilder();
              }
              userProto_ = input.readMessage(andy.entity.UserProtos.UserProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userProto_);
                userProto_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return andy.entity.UserProtos.internal_static_andy_entty_LoginProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return andy.entity.UserProtos.internal_static_andy_entty_LoginProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              andy.entity.UserProtos.LoginProto.class, andy.entity.UserProtos.LoginProto.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginProto> PARSER =
        new com.google.protobuf.AbstractParser<LoginProto>() {
      public LoginProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERPROTO_FIELD_NUMBER = 1;
    private andy.entity.UserProtos.UserProto userProto_;
    /**
     * <code>required .andy.entty.UserProto userProto = 1;</code>
     */
    public boolean hasUserProto() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .andy.entty.UserProto userProto = 1;</code>
     */
    public andy.entity.UserProtos.UserProto getUserProto() {
      return userProto_;
    }
    /**
     * <code>required .andy.entty.UserProto userProto = 1;</code>
     */
    public andy.entity.UserProtos.UserProtoOrBuilder getUserProtoOrBuilder() {
      return userProto_;
    }

    private void initFields() {
      userProto_ = andy.entity.UserProtos.UserProto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserProto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUserProto().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, userProto_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userProto_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static andy.entity.UserProtos.LoginProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static andy.entity.UserProtos.LoginProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static andy.entity.UserProtos.LoginProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static andy.entity.UserProtos.LoginProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static andy.entity.UserProtos.LoginProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static andy.entity.UserProtos.LoginProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static andy.entity.UserProtos.LoginProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static andy.entity.UserProtos.LoginProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static andy.entity.UserProtos.LoginProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static andy.entity.UserProtos.LoginProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(andy.entity.UserProtos.LoginProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code andy.entty.LoginProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:andy.entty.LoginProto)
        andy.entity.UserProtos.LoginProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return andy.entity.UserProtos.internal_static_andy_entty_LoginProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return andy.entity.UserProtos.internal_static_andy_entty_LoginProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                andy.entity.UserProtos.LoginProto.class, andy.entity.UserProtos.LoginProto.Builder.class);
      }

      // Construct using andy.entity.UserProtos.LoginProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserProtoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userProtoBuilder_ == null) {
          userProto_ = andy.entity.UserProtos.UserProto.getDefaultInstance();
        } else {
          userProtoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return andy.entity.UserProtos.internal_static_andy_entty_LoginProto_descriptor;
      }

      public andy.entity.UserProtos.LoginProto getDefaultInstanceForType() {
        return andy.entity.UserProtos.LoginProto.getDefaultInstance();
      }

      public andy.entity.UserProtos.LoginProto build() {
        andy.entity.UserProtos.LoginProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public andy.entity.UserProtos.LoginProto buildPartial() {
        andy.entity.UserProtos.LoginProto result = new andy.entity.UserProtos.LoginProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userProtoBuilder_ == null) {
          result.userProto_ = userProto_;
        } else {
          result.userProto_ = userProtoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof andy.entity.UserProtos.LoginProto) {
          return mergeFrom((andy.entity.UserProtos.LoginProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(andy.entity.UserProtos.LoginProto other) {
        if (other == andy.entity.UserProtos.LoginProto.getDefaultInstance()) return this;
        if (other.hasUserProto()) {
          mergeUserProto(other.getUserProto());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserProto()) {
          
          return false;
        }
        if (!getUserProto().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        andy.entity.UserProtos.LoginProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (andy.entity.UserProtos.LoginProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private andy.entity.UserProtos.UserProto userProto_ = andy.entity.UserProtos.UserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          andy.entity.UserProtos.UserProto, andy.entity.UserProtos.UserProto.Builder, andy.entity.UserProtos.UserProtoOrBuilder> userProtoBuilder_;
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      public boolean hasUserProto() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      public andy.entity.UserProtos.UserProto getUserProto() {
        if (userProtoBuilder_ == null) {
          return userProto_;
        } else {
          return userProtoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      public Builder setUserProto(andy.entity.UserProtos.UserProto value) {
        if (userProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userProto_ = value;
          onChanged();
        } else {
          userProtoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      public Builder setUserProto(
          andy.entity.UserProtos.UserProto.Builder builderForValue) {
        if (userProtoBuilder_ == null) {
          userProto_ = builderForValue.build();
          onChanged();
        } else {
          userProtoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      public Builder mergeUserProto(andy.entity.UserProtos.UserProto value) {
        if (userProtoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              userProto_ != andy.entity.UserProtos.UserProto.getDefaultInstance()) {
            userProto_ =
              andy.entity.UserProtos.UserProto.newBuilder(userProto_).mergeFrom(value).buildPartial();
          } else {
            userProto_ = value;
          }
          onChanged();
        } else {
          userProtoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      public Builder clearUserProto() {
        if (userProtoBuilder_ == null) {
          userProto_ = andy.entity.UserProtos.UserProto.getDefaultInstance();
          onChanged();
        } else {
          userProtoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      public andy.entity.UserProtos.UserProto.Builder getUserProtoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserProtoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      public andy.entity.UserProtos.UserProtoOrBuilder getUserProtoOrBuilder() {
        if (userProtoBuilder_ != null) {
          return userProtoBuilder_.getMessageOrBuilder();
        } else {
          return userProto_;
        }
      }
      /**
       * <code>required .andy.entty.UserProto userProto = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          andy.entity.UserProtos.UserProto, andy.entity.UserProtos.UserProto.Builder, andy.entity.UserProtos.UserProtoOrBuilder> 
          getUserProtoFieldBuilder() {
        if (userProtoBuilder_ == null) {
          userProtoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              andy.entity.UserProtos.UserProto, andy.entity.UserProtos.UserProto.Builder, andy.entity.UserProtos.UserProtoOrBuilder>(
                  getUserProto(),
                  getParentForChildren(),
                  isClean());
          userProto_ = null;
        }
        return userProtoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:andy.entty.LoginProto)
    }

    static {
      defaultInstance = new LoginProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:andy.entty.LoginProto)
  }

  public interface UserProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:andy.entty.UserProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string usesrname = 1;</code>
     */
    boolean hasUsesrname();
    /**
     * <code>required string usesrname = 1;</code>
     */
    java.lang.String getUsesrname();
    /**
     * <code>required string usesrname = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsesrnameBytes();

    /**
     * <code>required string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>required string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code andy.entty.UserProto}
   */
  public static final class UserProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:andy.entty.UserProto)
      UserProtoOrBuilder {
    // Use UserProto.newBuilder() to construct.
    private UserProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserProto defaultInstance;
    public static UserProto getDefaultInstance() {
      return defaultInstance;
    }

    public UserProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              usesrname_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return andy.entity.UserProtos.internal_static_andy_entty_UserProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return andy.entity.UserProtos.internal_static_andy_entty_UserProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              andy.entity.UserProtos.UserProto.class, andy.entity.UserProtos.UserProto.Builder.class);
    }

    public static com.google.protobuf.Parser<UserProto> PARSER =
        new com.google.protobuf.AbstractParser<UserProto>() {
      public UserProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USESRNAME_FIELD_NUMBER = 1;
    private java.lang.Object usesrname_;
    /**
     * <code>required string usesrname = 1;</code>
     */
    public boolean hasUsesrname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string usesrname = 1;</code>
     */
    public java.lang.String getUsesrname() {
      java.lang.Object ref = usesrname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          usesrname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string usesrname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsesrnameBytes() {
      java.lang.Object ref = usesrname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usesrname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>required string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      usesrname_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUsesrname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsesrnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsesrnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static andy.entity.UserProtos.UserProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static andy.entity.UserProtos.UserProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static andy.entity.UserProtos.UserProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static andy.entity.UserProtos.UserProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static andy.entity.UserProtos.UserProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static andy.entity.UserProtos.UserProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static andy.entity.UserProtos.UserProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static andy.entity.UserProtos.UserProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static andy.entity.UserProtos.UserProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static andy.entity.UserProtos.UserProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(andy.entity.UserProtos.UserProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code andy.entty.UserProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:andy.entty.UserProto)
        andy.entity.UserProtos.UserProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return andy.entity.UserProtos.internal_static_andy_entty_UserProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return andy.entity.UserProtos.internal_static_andy_entty_UserProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                andy.entity.UserProtos.UserProto.class, andy.entity.UserProtos.UserProto.Builder.class);
      }

      // Construct using andy.entity.UserProtos.UserProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        usesrname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return andy.entity.UserProtos.internal_static_andy_entty_UserProto_descriptor;
      }

      public andy.entity.UserProtos.UserProto getDefaultInstanceForType() {
        return andy.entity.UserProtos.UserProto.getDefaultInstance();
      }

      public andy.entity.UserProtos.UserProto build() {
        andy.entity.UserProtos.UserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public andy.entity.UserProtos.UserProto buildPartial() {
        andy.entity.UserProtos.UserProto result = new andy.entity.UserProtos.UserProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.usesrname_ = usesrname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof andy.entity.UserProtos.UserProto) {
          return mergeFrom((andy.entity.UserProtos.UserProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(andy.entity.UserProtos.UserProto other) {
        if (other == andy.entity.UserProtos.UserProto.getDefaultInstance()) return this;
        if (other.hasUsesrname()) {
          bitField0_ |= 0x00000001;
          usesrname_ = other.usesrname_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsesrname()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        andy.entity.UserProtos.UserProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (andy.entity.UserProtos.UserProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object usesrname_ = "";
      /**
       * <code>required string usesrname = 1;</code>
       */
      public boolean hasUsesrname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string usesrname = 1;</code>
       */
      public java.lang.String getUsesrname() {
        java.lang.Object ref = usesrname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            usesrname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string usesrname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsesrnameBytes() {
        java.lang.Object ref = usesrname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usesrname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string usesrname = 1;</code>
       */
      public Builder setUsesrname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        usesrname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string usesrname = 1;</code>
       */
      public Builder clearUsesrname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        usesrname_ = getDefaultInstance().getUsesrname();
        onChanged();
        return this;
      }
      /**
       * <code>required string usesrname = 1;</code>
       */
      public Builder setUsesrnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        usesrname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>required string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>required string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:andy.entty.UserProto)
    }

    static {
      defaultInstance = new UserProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:andy.entty.UserProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_andy_entty_LoginProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_andy_entty_LoginProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_andy_entty_UserProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_andy_entty_UserProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032andy/netty/UserProto.proto\022\nandy.entty" +
      "\"6\n\nLoginProto\022(\n\tuserProto\030\001 \002(\0132\025.andy" +
      ".entty.UserProto\"0\n\tUserProto\022\021\n\tusesrna" +
      "me\030\001 \002(\t\022\020\n\010password\030\002 \002(\tB\031\n\013andy.entit" +
      "yB\nUserProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_andy_entty_LoginProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_andy_entty_LoginProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_andy_entty_LoginProto_descriptor,
        new java.lang.String[] { "UserProto", });
    internal_static_andy_entty_UserProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_andy_entty_UserProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_andy_entty_UserProto_descriptor,
        new java.lang.String[] { "Usesrname", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
